### ISSUE TITLE
SafeConfigParser no longer exists till Python 3.11

### ISSUE THREAD

**Issue by renaudflavigny** [JimmXinu/EpubSplit#14] opened 2024-07-16 13:14 UTC
The class SafeConfigParser no longer exists in module ConfigParser till python 3.11. In consequence, ePubSplit could'nt be installed in python > 3.11 (current version of python is 3.12)

SafeConfigParser is replaced with ConfigParser.

File epubsplit_plugin.py could be changed line 19 : change SafeConfigParser with ConfigParser.

Work fine on my config : 
Calibre 7.14
ePubSplit 3.7.0
python 3.12.4

**Comment by JimmXinu** [comment] 2024-07-16 13:57
Duplicate of #13 and already addressed in c13dbd71723d5f2e900fb43e6802f2b28126fb47

I hadn't released plugin with the change yet, but I'll do so now.

**Closed by JimmXinu** 2024-07-16 13:57 UTC
